#-------------------- Params --------------------
samplesheet: "/farmshare/home/classes/bios/270/data/samplesheet.csv"
transcriptome: "/farmshare/home/classes/bios/270/data/ecoli_ref/GCF_000401755.1_Escherichia_coli_ATCC_25922_cds_from_genomic.fna"
  #index: '/farmshare/home/classes/bios/270/data/indexes/ecoli_transcripts_index'
#outdir: '/farmshare/user_data/khoang99/bios270/data/processed_data/SRP628437_nf'  modify to your directory
outdir: '/farmshare/user_data/masarus/repos/BIOS270-AU25/Pipeline/SRP628437_nf'
run_deseq: true
